# Generated by Django 2.0.5 on 2018-06-04 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plasma_params', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasmaSpecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('H', 'Hydrogen'), ('E', 'Electron'), ('D', 'Deuterium'), ('T', 'Tritium')], max_length=15)),
                ('density_axis', models.FloatField()),
                ('density_surface', models.FloatField()),
                ('temperature_axis', models.FloatField()),
                ('temperature_surface', models.FloatField()),
                ('plasma_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', related_query_name='species', to='plasma_params.PlasmaParameter')),
            ],
        ),
    ]
