# Generated by Django 2.0.5 on 2018-05-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestep', models.FloatField(default=0.01)),
                ('mesh_point', models.SmallIntegerField(default=50)),
                ('snap_data_print', models.SmallIntegerField(default=10)),
                ('radial_profile_snap', models.SmallIntegerField(default=100)),
                ('time_evolution_snap', models.SmallIntegerField(default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
