# Generated by Django 2.0.5 on 2018-06-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.CharField(default='HT-6M', max_length=12)),
                ('major_radius', models.FloatField(default=0.65)),
                ('minor_radius', models.FloatField(default=0.2)),
                ('triangularity', models.FloatField(default=0)),
                ('ellipticity', models.FloatField(default=1)),
                ('plasma_current', models.FloatField(default=0.04)),
                ('magnetic_field', models.FloatField(default=1.5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
