# Generated by Django 2.0.5 on 2018-05-12 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major_radius', models.FloatField(default=0.65)),
                ('minor_radius', models.FloatField(default=0.2)),
                ('triangularity', models.FloatField(default=0)),
                ('ellipticity', models.FloatField(default=1)),
                ('plasma_current', models.FloatField(default=0.04)),
                ('magnetic_field', models.FloatField(default=1.5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_device_params', related_query_name='created_device_params', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_device_params', related_query_name='updated_device_params', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
