# Generated by Django 2.0.5 on 2018-06-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_params', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceparameter',
            name='machine',
            field=models.CharField(default='HT-6M', max_length=12),
        ),
    ]
