# Generated by Django 2.0.5 on 2018-05-19 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nbi_power', models.FloatField(default=0)),
                ('nbi_radial_position', models.FloatField(default=0)),
                ('nbi_radial_width', models.FloatField(default=0.5)),
                ('icrf_power', models.FloatField(default=0)),
                ('icrf_radial', models.FloatField(default=0)),
                ('icrf_radial_width', models.FloatField(default=0.5)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_params', related_query_name='heat_params', to='scenarios.Scenario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
