# Generated by Django 2.0.5 on 2018-06-04 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_params', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break_point_number', models.PositiveIntegerField(default=2)),
                ('breakpoint_time', models.FloatField(default=0)),
                ('timestep', models.FloatField(default=0.01)),
                ('particle_species', models.CharField(choices=[('H', 'Hydrogen'), ('E', 'Electron'), ('D', 'Deuterium'), ('T', 'Tritium')], default='H', max_length=2)),
                ('rate_of_particle_source', models.FloatField(default=0)),
                ('radial_position', models.FloatField(default=0)),
                ('radial_width', models.FloatField(default=0.5)),
                ('nbi_power', models.FloatField(default=0)),
                ('nbi_radial_position', models.FloatField(default=0)),
                ('nbi_radial_width', models.FloatField(default=0.5)),
                ('icrf_power', models.FloatField(default=0)),
                ('icrf_radial', models.FloatField(default=0)),
                ('icrf_radial_width', models.FloatField(default=0.5)),
                ('control_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_params', related_query_name='heating_params', to='control_params.ControlParameter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
