# Generated by Django 2.0.7 on 2018-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('heating_params', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatingparameter',
            name='particle_species',
            field=models.CharField(choices=[('H', 'H'), ('E', 'E'), ('D', 'D'), ('T', 'T')], default='H', max_length=2),
        ),
    ]
