# Generated by Django 2.0.5 on 2018-05-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heating_params', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatingparameter',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_params', related_query_name='heating_params', to='scenarios.Scenario'),
        ),
    ]
