# Generated by Django 2.0.7 on 2018-07-23 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('advanced_cases', '0002_advancedcase_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedcase',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='advance_cases', related_query_name='advance_case',
                                    to='scenarios.Scenario'),
        ),
    ]
