# Generated by Django 2.0.5 on 2018-06-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_model', models.CharField(default='CDBM05', max_length=20)),
                ('resistivity', models.CharField(default="Hinton and Hazeltine's model", max_length=40)),
                ('particle_diffusion', models.CharField(default='Model01', max_length=40)),
                ('heat_pinch', models.CharField(default='Pinch01', max_length=40)),
                ('bootstrap_current', models.CharField(default='Model01', max_length=20)),
                ('neoclassical', models.CharField(default='Model01', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
