# Generated by Django 2.0.5 on 2018-05-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resistivity', models.PositiveSmallIntegerField(default=1)),
                ('particle_diffusion', models.PositiveSmallIntegerField(default=1)),
                ('heat_pinch', models.PositiveSmallIntegerField(default=1)),
                ('bootstrap_current', models.PositiveSmallIntegerField(default=1)),
                ('neoclassical', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
