# Generated by Django 2.0.6 on 2018-06-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_remove_result_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='scenario',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
