# Generated by Django 2.0.7 on 2018-07-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plasma_params', '0002_auto_20180718_1706'),
        ('scenarios', '0003_auto_20180624_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='density_temp_params',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='densities_and_temperatures', related_query_name='density_and_temperature', to='plasma_params.DensityAndTemperature'),
        ),
    ]
