# Generated by Django 2.0.7 on 2018-07-18 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_scenario_density_temp_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='density_temp_params',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='densities_and_temperatures', related_query_name='density_and_temperature', to='plasma_params.DensityAndTemperature'),
            preserve_default=False,
        ),
    ]
